### ISSUE TITLE
Unreal 5 source control not working correctly?

### ISSUE THREAD

**Issue by markusstephanides** [ProjectBorealis/UE4GitPlugin#10]
Hello!

Just tried the most recent commit in a fresh Unreal 5 file with the latest UE5 EA2 Build. It kinda works but there are some weird things. For example I can't update the project within the editor. There isn't such a field. Also when I save an asset, Unreal doesn't ask me whether I want to check it out. It seems to check out the asset in the background but I can only see that it is checked if I right-click on the asset and press on Refresh.

Is this a plugin issue or a general UE5 source control issue?

**Comment by mastercoms** [comment]
Since we're not using UE5 at this time, we haven't battle tested it and suited it entirely to the new UE5 workflow. It is, however, as far as I am aware, at least as functional as the built-in Git plugin Epic maintains. However, last I checked, Epic has only done minimal adjustments to all source control plugins besides Perforce in UE5. Contributions are welcome if you'd like to improve the experience in UE5.

**Comment by Flaberik** [comment]
Hello, can you tell me if this fork works exactly on Ue5? For some reason I don't have tabs (Sync/Pull | Submite | Push ). Or is it somehow done differently in Ue5?

**Comment by mastercoms** [comment]
The UE5 changes are the UE4 plugin, but applying what Epic changed to get the plugin working in UE5. There is no new functionality or anything accommodating for UE5 besides basic API fixes.

**Comment by mastercoms** [comment]
Thanks to @rweber89 in #11, a source control menu has been added, so you can submit, pull, push and refresh. I'm not sure about the background checkout not updating, please let me know if this still happens.

**Comment by rweber89** [comment]
@mastercoms I think I've observed an issue whilst using UE5. Whilst the checkout is working, the assets aren't refreshed. So if you launch the editor with assets that are already checkedout it won't display this until you refresh manually. I'll look into this when I get time.

**Comment by mastercoms** [comment]
Fixed now, thank you for the PRs!
