### ISSUE TITLE
Git not found in %PATH%

### ISSUE THREAD

**Issue by Chreas** [ProjectBorealis/UE4GitPlugin#100]
I've just installed the plugin in a project and connected it to our source control. But when I try to check out any file, I get the following erros. Probably important note: the whole git (and LFS) setup of the project was already done through an external application (Fork). I've installed the plugin to get access to the lock functionality inside the editor.

SourceControl: Error: Error: failed to find `git rev-parse --git-dir --show-toplevel`: executable file not found in %PATH%
SourceControl: Error: Error reading `git config`: executable file not found in %PATH%
SourceControl: Error: Unable to create lock system: failed to find `git rev-parse --show-toplevel`: executable file not found in %PATH%
SourceControl: Error: Error: failed to find `git rev-parse --git-dir --show-toplevel`: executable file not found in %PATH%
SourceControl: Error: Error reading `git config`: executable file not found in %PATH%
SourceControl: Error: Unable to create lock system: failed to find `git rev-parse --show-toplevel`: executable file not found in %PATH%

**Comment by mastercoms** [comment]
This seems more like a Git command line issue, do you have that installed properly?

**Comment by Chreas** [comment]
Thanks for the quick answer! I think I've installed it properly. But then again - in what way could there be an improper setup if I installed it by using the installer from https://git-scm.com/downloads?

the command line shows:
git version 2.40.1.windows.1
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)

So that should be the newest version.


Another possibly important addition:
I'm on UE 5.1.1, and the plugin didn't work when I added it to our project --> when the plugin was in the Plugins/ directory within the project, I couldn't open the project any more.

so here the steps I took to make the plugin "work" in our project (that does use Blueprints):
- set up a new project with the Games + C++ Defaults
- installed all the necessary Visual Studio components
- added the UEGitPlugin Folder to /Plugins/ in the project
- right click the UE Project and chose "Generate Visual Studio project files"
- open the project: now it's opening
- copying the UEGitPlugin Folder into the actual project, which now can open
- configuring the Source Control and get the green checkmark next to "Source Control"

**Comment by mastercoms** [comment]
That's very strange, is there a path listed in source control settings for Git binary path? Also, does the plugin work with this version: https://github.com/ProjectBorealis/UEGitPlugin/archive/5c596b5ed29edfab2f62278e00c395ca5220d6a4.zip

> Another possibly important addition:
I'm on UE 5.1.1, and the plugin didn't work when I added it to our project --> when the plugin was in the Plugins/ directory within the project, I couldn't open the project any more.

This is just because we do not provide pre-built binaries.

**Comment by Chreas** [comment]
Ok with this download it does not show the error anymore. Check Out works. But "Submit Content" does not show any changes when files are changed = there's something else not working.

**Comment by mastercoms** [comment]
This should be fixed in the latest version
