### ISSUE TITLE
Issue on 5.2 Release

### ISSUE THREAD

**Issue by loko087** [ProjectBorealis/UE4GitPlugin#102]
Hi! As usual thanks for this great plugin,

I am getting an error regarding 
  GitSourceControlModule.h(138): [C2259] 'FGitSourceControlProvider': cannot instantiate abstract class
  
  
  Apparently it might be due to the plugin missing functions abstract functions:
  I found Login, and SwitchWorkspace  https://docs.unrealengine.com/5.2/en-US/API/Developer/SourceControl/ISourceControlProvider/ 
  
  Could this be missing?
  
  Thanks!

**Comment by loko087** [comment]
Wait I think it's different functions 
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/7088623/d2867641-a631-41b0-9836-1b61064f4371)

**Comment by as3mbus** [comment]
hello is there any change you did to fix this.

i see this issue closed without actual commit / changes

**Comment by loko087** [comment]
Update to the latest version of the plugin, it got properly fixed afterwards
