### ISSUE TITLE
UE5.2 missing icons in submit dialog

### ISSUE THREAD

**Issue by Schroedingers-Cat** [ProjectBorealis/UE4GitPlugin#104]
The submit dialog is missing the file status icons since v5.2. While the screenshots are made on Linux, it's also happening on Windows:
![missing status icons in 5.2.0 on Linux](https://github.com/ProjectBorealis/UEGitPlugin/assets/6382400/d33d0c7e-b235-4091-8b91-eefda8bed89d)

It's working alright with v5.1.1:
![status icons in v5.1.1 on Linux](https://github.com/ProjectBorealis/UEGitPlugin/assets/6382400/e03a82b9-99d3-4b23-a040-e338d1fe4c59)

I'm using the prebuilt UE5 binaries from Epic  and the git plugin is installed into the project scope (not engine-wide).  

neofetch output:
```
OS: Manjaro Linux x86_64 
Host: X570 Steel Legend 
Kernel: 6.3.0-1-MANJARO 
Uptime: 1 hour, 49 mins 
Packages: 1699 (pacman), 14 (flatpak) 
Shell: zsh 5.9 
Resolution: 3840x2160 
DE: GNOME 43.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adw [GTK2/3] 
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz 
GPU: AMD ATI Radeon RX 6900 XT 
Memory: 6170MiB / 128736MiB 
```

**Comment by mastercoms** [comment]
5.2 completely changed the icons

**Comment by Schroedingers-Cat** [comment]
I must have missed that when I tested 5.2 on Windows. then. So it's an issue on all platforms?

**Comment by mastercoms** [comment]
Not sure why it's only affecting you on Linux, but yes there is a all-platforms icon update in 5.2.

**Comment by Schroedingers-Cat** [comment]
I must have forgotten to check this on Win. It's also happening there with the current main branch installed as project-scope plugin on Windows:
![grafik](https://github.com/ProjectBorealis/UEGitPlugin/assets/6382400/8aa8835b-ced2-417a-9fad-cf65bf2a7c0b)

So it's not platform-specific. I'll update the issue title and the description.
