### ISSUE TITLE
git-lfs locks not works

### ISSUE THREAD

**Issue by eranfu** [ProjectBorealis/UE4GitPlugin#109]
After I submit the changes, The file still be locked.
Then I run `git-lfs locks` on console. But the result is empty:
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/27914183/b711fbdd-8f30-4279-8147-867bfe32b58d)

But actually, the file is still locked:
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/27914183/37e8bc48-37fc-408e-bf1a-c5a0b750c1d5)
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/27914183/ba77f647-912a-4ce9-9469-f270701beeb0)

System: Windows 11
Unreal Engine Version: 5.2

Help me please. Thanks!

**Comment by eranfu** [comment]
The branch is release.

**Comment by mastercoms** [comment]
What is the git server?

**Comment by eranfu** [comment]
> What is the git server?

It is a self-developed server by my company.

**Comment by mastercoms** [comment]
Does the `git lfs locks` function in any other circumstances?

**Comment by mastercoms** [comment]
Going to close this for now
