### ISSUE TITLE
Unclear recommendation in readme.md, duplicate snippets but descriptions indicate opposite

### ISSUE THREAD

**Issue by namrog84** [ProjectBorealis/UE4GitPlugin#119]
It appears like in the Recommended section
https://github.com/ProjectBorealis/UEGitPlugin#recommended

That both snippets of code are identical, I think 1 of them should be inverted of the other one? Unless I am misunderstanding the text.

> ...
> (but requires user attention to excessive locking of content):
```
[/Script/UnrealEd.EditorLoadingSavingSettings]
bAutomaticallyCheckoutOnAssetModification=False
bPromptForCheckoutOnAssetModification=True
```
>  OR, to enable auto-prompt on modification, which is a bit more upfront/intrusive in user flows, but more conservative with locking, flip the settings:
```
[/Script/UnrealEd.EditorLoadingSavingSettings]
bAutomaticallyCheckoutOnAssetModification=False
bPromptForCheckoutOnAssetModification=True
```

**Comment by DmitriiBobrovnikov** [comment]
For the system to work properly and be able to revertin (Unlock) files, you need to
  - username for git lfs 2 plugin matched repository account name
  
  
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/36227870/0ae3d19a-68a8-41ee-a086-bbeccf50689b)

![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/36227870/4c748927-a224-4f1d-b7d8-1e64713e4c8f)
