### ISSUE TITLE
Revision Control menu Flickering profusely when there are 2 editor window

### ISSUE THREAD

**Issue by as3mbus** [ProjectBorealis/UE4GitPlugin#120]
![60VRmW2nKR](https://github.com/ProjectBorealis/UEGitPlugin/assets/16043293/49f73848-383c-4f58-a3a4-326d1c2c398e)

it only happen in my device. and idk what causes it.

the gif are recorded at smaller framerate thus not able to represent actual condition

**Comment by mastercoms** [comment]
Does this happen with other source control plugins?

**Comment by as3mbus** [comment]
as i don't use other version control. i can't check.

but what i can check it also happen with disabled source control

below i add additional detail on unreal editor.
Version: 5.2.1-26001984+++UE5+Release-5.2
Platform: Windows 11 (22H2) [10.0.22621.2134] (x86_64

then it maybe caused by my version of unreal instead of git plugin 🤔

**Comment by mastercoms** [comment]
Closing this then, hopefully Epic fixes it!
