### ISSUE TITLE
"Revision Control is Disabled" msg

### ISSUE THREAD

**Issue by oivio** [ProjectBorealis/UE4GitPlugin#123]
I come a cross strange bug or maybe it is a setting that I did not seen yet.

At start of editor I do get error "Revision Control is Disabled":
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/38628851/4d957a75-bf07-45bc-b10f-9ebb91e503e6)

If I leave this as it is it leads me to GitConnection errors when I try to PULL or Submit Content.
It all works fine if I with every editor start I go to Revision Control Settings and press "Accept Settings". Feels like it do not by default automatically accept settings at start of editor.

Could be that an issue?
`LogModuleManager: Warning: GetModule racing against IsReady: GitSourceControl
`

**Comment by mastercoms** [comment]
Does it ever come enabled if you wait without opening revision control? This Git plugin has a deferred startup so it should come online shortly after editor start. Opening the settings may be interfering with this process.
