### ISSUE TITLE
Source control icons don´t work in current release branch (UE 5.1.1)

### ISSUE THREAD

**Issue by IllustrisJack** [ProjectBorealis/UE4GitPlugin#127]
As described icons don´t seem to work in the current release branch (commit 3f7000770b1ef5034fde2841d42de894df8229d8).

Engine Version: 5.1.1

Haven´t done any backtracking to when exactly they stop working but wanted to give a heads up. Release 3.11 works for us.

**Comment by mastercoms** [comment]
Could you see if 3.12 works?

**Comment by IllustrisJack** [comment]
Just tested, 3.12 seems to work aswell.
