### ISSUE TITLE
Blueprints reported as changed when changes made only in parent

### ISSUE THREAD

**Issue by Louspirit** [ProjectBorealis/UE4GitPlugin#135]
Hello,

When editing a parent blueprint (like adding a variable) and saving, it triggers a source change in all its children's blueprints.

I have had this bug for quite some time, and I'm tired of having to diff one by one to revert them all finally.
    👉The diff in children shows no modification, or '_Move node None is right revision_'.

Maybe we can't do much, but it is worth asking. 🤔

**Comment by mastercoms** [comment]
This is most likely an issue in Unreal Engine, and maybe something of the class setup that causes dirtying across Blueprints. So not something we could fix in the plugin, unfortunately.

**Comment by Louspirit** [comment]
Thanks for the answer @mastercoms. 
Nonetheless, something that could help in the matter would be a content folder filter for version control touched files.
Have you ever been able to achieve that?
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/2952456/a946d606-cbb3-4c12-87a2-b777ba078257)

I am also looking for a keyboard shortcut to _Diff against Repo_?

Currently, I have to manually go back and forth between Sourcetree and UE to search file by name. Tiring when I have dozens of file to review...
