### ISSUE TITLE
Can't connect to source control: Failed Git remote connection

### ISSUE THREAD

**Issue by cwsimms** [ProjectBorealis/UE4GitPlugin#136]
I created a blank project and followed all the steps in the readme. 
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/12941211/0d2a2a60-dbe2-4476-828a-b7b9b334b7f0)

However, when I press "Accept Settings" in the Source Control Login window, it fails to connect. The repo has been intialized locally.

**Comment by lburini** [comment]
Make sure to run this command on git console:
`git remote add origin YOUR_REPOSITORY_URL`
then, try again

**Comment by mastercoms** [comment]
What git host are you using?

**Comment by MalikuMane** [comment]
I see this issue too when using a repository with no remote. Suppose an adhoc project is created with a few git commits to allow use UE's blueprint diff tool to view changes between versions of a marketplace project. This works fine with the git plugin that comes with the editor but not this one.

**Comment by MalikuMane** [comment]
It works fine with no host if you just uncheck "Uses Git LFS"
