### ISSUE TITLE
After Check-In, Object can not be checked out

### ISSUE THREAD

**Issue by ChilledCosmonaut** [ProjectBorealis/UE4GitPlugin#141]
Hi. So we are currently facing the problem that when we check in an arbitrary object and apply some changes to it, the option to check out is greyed out. Is this intended? Are there any extra steps missing?

![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/65485319/5c70ed87-54d0-478a-a4ba-fb6dfa51be0c)

**Comment by mastercoms** [comment]
Do you have your LFS username set in revision control settings properly?

**Comment by ChilledCosmonaut** [comment]
Yes. The username is the same for Revision control and Git LFS. Also the username is the same for the remote gitlab installation. Are there any other settings I can try?

**Comment by ChilledCosmonaut** [comment]
Sorry got it now. It seems the name auto generated for Git LFS is wrong and then it does not detect the PC as the same user
