### ISSUE TITLE
Diffing is broken if there is a space in a folder name

### ISSUE THREAD

**Issue by dtb49** [ProjectBorealis/UE4GitPlugin#158]
Probably a pretty silly issue but, finally after debugging for a while a co-worker found this fix to a diffing bug. If a folder contains a space then all diffing attempts will end with the following error:

```
LogSourceControl: RunDumpToFile: 'git -C "D:/simvana-anesthesia" cat-file --filters e1c91607b25fbae7289316a3d74b1c51ac10272c:Unreal Projects/Anesthesia/Content/Anesthesia/Base/Components/SC_Base_DisplayScreen.uasset'
LogSourceControl: Error: DumpToFile: ReturnCode=129
```
We tracked it to the RunDumpToFile function line 1776 of GitSourceControlUtils.cpp
if you change this line to the following below it seems to resolve the issue.

`FullCommand += TEXT("\"") + InParameter + TEXT("\"");`

Obviously this can be prevented by not allowing spaces in folder names but, we were converting a legacy project to git and came across this.

**Comment by mastercoms** [comment]
Thanks! We definitely want to catch and fix anything like that. It's very silly for software not to support spaces in file names.

**Comment by mastercoms** [comment]
I've applied your suggested fix, but I definitely would rather at some point to go through and see if we can pass in a safe arguments array so we don't have to do unsafe string manipulation to accumulate parameters.
