### ISSUE TITLE
UE4 Error HEAD...origin/evelop

### ISSUE THREAD

**Issue by stilobique** [ProjectBorealis/UE4GitPlugin#16]
Hello,
i'm look to test your plugin version with Unreal 5, i have some issue with the Source Control and... i don't understand why the head look a bad name, my branch are `develop` and `main`, and i use the `dev.`. I'm not a C++ programmer, but if i can give more information i'm here :) .

I used your branch `pb-changes-ue5`.

```
LogSourceControl: Warning: RunCommand(locks) ReturnCode=2:
Error while retrieving locks: exit status 127
LogSourceControl: Warning: RunCommand(locks) ReturnCode=2:
Error while retrieving locks: no cached locks present
LogSourceControl: Warning: RunCommand(diff) ReturnCode=128:
fatal: bad revision 'HEAD...origin/evelop'
SourceControl: Error: fatal: bad revision 'HEAD...origin/evelop'
```

**Comment by mastercoms** [comment]
This was an untested pathway since we use status branches, thank you for the report. It has been fixed in d1262d7e6ac558006eb4ac9b2e68c438dc4f37d6!
