### ISSUE TITLE
Lock is not being reverted after checking out a modified file

### ISSUE THREAD

**Issue by ThatDudeLawr** [ProjectBorealis/UE4GitPlugin#163]
I cannot manage to revert a file and have its lock removed after modifying it.

Steps to reproduce:
1. Open a file
2. Change some values inside of it
3. Save the file and have it checked out/locked
4. Revert that file
5. Notice that the file is being reverted but kept locked (with a different icon as in a different user has it locked)

![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/32162117/d24f9e8d-e61c-457e-878d-8893cc5654d6)

Edit: 
If I'm manually checking out the file before modifying the file and reverting it afterwards this issue is not occurring.

**Comment by mastercoms** [comment]
Make sure your lfs locking username is set correctly. For the git plugin, reverts take 2 steps: revert content, then revert lock.

**Comment by ThatDudeLawr** [comment]
I think that was it. 

In case there are other people with a similar issue, I am using Azure Devops and apparently there was a conflict between the Full Name on the Azure Devops account (which I believe it's the username used by it) and the Git/Unreal Username on my PC. Once I changed my name to match in all places it worked. Thank you!
