### ISSUE TITLE
ISourceControlRevision::Get signature changed in latest 5.0 source builds

### ISSUE THREAD

**Issue by ameaninglessname** [ProjectBorealis/UE4GitPlugin#17]
https://github.com/EpicGames/UnrealEngine/commit/10d4800edee9cb8c79d37a8b8a8951fda9ed0d16
in this commit, 
`bool Get( FString& InOutFilename ) const;` changed to
`bool Get(FString& InOutFilename, EConcurrency::Type InConcurrency = EConcurrency::Synchronous) const`

which result in a compile error in ue5-main branch.

**Comment by mastercoms** [comment]
I'm not sure if there's a good way to detect this and I'd prefer keeping the default branch compatible with EA. Since if a user compiled main, they probably can fix it manually for now. We could also have a new branch for it.

**Comment by rweber89** [comment]
> I'm not sure if there's a good way to detect this and I'd prefer keeping the default branch compatible with EA. Since if a user compiled main, they probably can fix it manually for now. We could also have a new branch for it.

That's easily detectable. I'll make a PR, but I won't be compiling it. So if @ameaninglessname could compile and verify that it works, that'd be great, before the PR is merged! 🙏

**Comment by ameaninglessname** [comment]
> 

That would be nice, I'm willing to help 😀

**Comment by rweber89** [comment]
> That would be nice, I'm willing to help 😀

I deleted my earlier comment because it wasn't relevant any longer after I checked out the ue5-main source code.
No need to test, I know it'll work and the PR is up 😄

**Comment by mastercoms** [comment]
Don't think we should close this for now, since it does give those who encounter this issue a helpful tip on how to fix it.

**Comment by mastercoms** [comment]
Issues still get pinned while closed actually, so closing!
