### ISSUE TITLE
Plugin not working with 5.4.3?

### ISSUE THREAD

**Issue by Mets3D** [ProjectBorealis/UE4GitPlugin#175]
Hi. First time user, maybe I'm doing something wrong.

When trying to place the plugin into my Project's Plugins folder, then opening the project, I get:
![image](https://github.com/user-attachments/assets/f1a8f366-9e25-4a03-809a-198da9e9b108)

Of course clicking "Yes" in this dialogue doesn't do anything, it just quits.
I tried renaming the folder to `GitSourceControl`, but no difference.

When trying to place the plugin into the engine's Plugins folder, I get essentially the same error:
![image](https://github.com/user-attachments/assets/613298d9-42e7-4faf-b2bf-d3db235550ae)

I even tried downloading a slightly older version of the plugin, namely this commit:
https://github.com/ProjectBorealis/UEGitPlugin/commit/726b4a7944fec46c398110cc209f47b9300ce06a

But I got exactly the same results.

Advice would be greatly appreciated.

**Comment by mastercoms** [comment]
What do your logs say about the failure (in Saved/Logs)?

**Comment by Mets3D** [comment]
The log: [PinballTD.log](https://github.com/user-attachments/files/16632086/PinballTD.log)

I have sort of found a solution. My friend who knows more than me simply re-compiled the plugin in Visual Studio, and gave me the resulting files. And that just worked...! Does that make any sense?

**Comment by mastercoms** [comment]
Yes that makes sense, we don't provide precompiled binaries at this time so you have to build with Visual Studio

**Comment by Mets3D** [comment]
Hmm, okay, that makes sense, but I think a line about that in that Installation section of the ReadMe wouldn't hurt? Although apparently I'm the only one dumb enough to not realize that having to compile UE plugins downloaded from git is an implied requirement.
