### ISSUE TITLE
Unable to lock files

### ISSUE THREAD

**Issue by ThatCreeper** [ProjectBorealis/UE4GitPlugin#25]
I am unable to see a "Check Out" button when right clicking, nor am I able to see the "Checked out by" text when I manually lock a file in the terminal.

I'm running UE 4.27.2 with the release branch of this.

**Comment by mastercoms** [comment]
What are your .gitattributes?

**Comment by ThatCreeper** [comment]
Just the default
```
Content/** filter=lfs diff=lfs merge=lfs -text lockable
```

**Comment by mastercoms** [comment]
I haven't updated the repo initialization, but you should use this one: https://github.com/ProjectBorealis/Base-Project/blob/main/.gitattributes

**Comment by ThatCreeper** [comment]
Thank you!
