### ISSUE TITLE
error CS0101: The namespace `global::' already...

### ISSUE THREAD

**Issue by OdinVex** [ProjectBorealis/UE4GitPlugin#29]
error CS0101: The namespace `global::' already contains a definition for `GitSourceControl'

This issue should be added into the README: https://github.com/SRombauts/UE4GitPlugin/issues/94

**Comment by mastercoms** [comment]
I'll add a fixes section to the wiki and note this. Personally, we rename the original plugin to GitSourceControl.uplugin.disabled. We could also rename the namespace temporarily.

**Comment by SRombauts** [comment]
Hello there

On my end, I have writen quite clearly in the README for some time now that the best way is to add it to your project's Plugin/ folder:
https://github.com/SRombauts/UE4GitPlugin/blob/master/README.md 

```
Install this Git Plugin (dev) into your Game Project
Unreal Engine comes with a stable version of this plugin, so no need to install it.

This alternate "Git development plugin" needs to be installed into a subfolder or your Game Project "Plugins" directory (that is, you cannot install it into the Engine Plugins directory):

<YourGameProject>/Plugins
You will obviously only be able to use the plugin within this project.
```

Cheers!
Sébastien

**Comment by OdinVex** [comment]
> Hello there
> ...
> Cheers! Sébastien

I had to remove the Engine/Plugin/Developer/GitSourceControl for it to compile on Linux. Yes, even as a Plugin for Project-only.
