### ISSUE TITLE
No Assets To Check In

### ISSUE THREAD

**Issue by loko087** [ProjectBorealis/UE4GitPlugin#32]
So am trying to figure this one out, but it seems like I get the current behavior:

1. Git Attributes are properly configured
2. I checkout a material uasset
3. It shows the red check mark (great)
4. I save the file, go back to  "submit" the file
5. It says there's no files to submit, it shows the file locked... by me, I can't unlock it from the editor, only from the command line

Am I doing something wrong here?

**Comment by loko087** [comment]
NVM I figured it out, 
just a pointer
![imagen](https://user-images.githubusercontent.com/7088623/157607510-e070f1ba-95c3-4994-abff-ff27a3860eb3.png)

Docs state that the user for lfs flow is the same as above, but it's not, it's the actual username you are using to submit on your repo.

**Comment by hiimawalrus** [comment]
this fixed it for me, thanks!
