### ISSUE TITLE
Editor locks up when attempting to enable the Source Control integration

### ISSUE THREAD

**Issue by jeffason** [ProjectBorealis/UE4GitPlugin#33]
I'm using the Unreal Engine 4.27.2 binary distribution

**Comment by jeffason** [comment]
I found this was due to my SSH key having a passphrase set - would be awesome to handle this case better than what appears to be a deadlock,  Here are some trouble-shooting steps I encountered while getting this plugin to work for our team, thought I'd share to help the next person!

## Troubleshooting

### **Editor freezes when enabling source control**

If you use SSH authentication, remove the passphrase from your key

1. `ssh-keygen -p`
2. Specify the location of your SSH private key
3. Enter existing passphrase for the private key
4. Press [ENTER] twice without entering any passphrase to remove current passphrase

### **Git command failed. Please check your connection and try again...**

Ensure your local branch is pushed to your remote

### **Failed to load content (while diffing)**

Delete the contents in your workspace’s `Saved\Diff\*` folder

### **Files on disk are not read-only or I am not prompted to check out the file**

1. Stash or commit your work to your local branch
2. Perform a `git checkout .`

**Comment by jeffason** [comment]
awesome work btw!

**Comment by mastercoms** [comment]
I think with async init, this is solved now. Doesn't timeout though. Let me know if it still doesn't work.
