### ISSUE TITLE
Cannot create an asset where another asset with the same name was previously deleted

### ISSUE THREAD

**Issue by Acren** [ProjectBorealis/UE4GitPlugin#34]
Hello, great plugin!

I've found an issue that can be easily reproduced in both 4.27 and 5.0.

1. In Unreal, create any asset (e.g. a material: "NewMaterial") at any content location.
2. Commit the asset.
3. Delete the asset. This should work fine and remove the asset from disk, and Git will detect it as a removal.
4. Finally, create an asset in the same place with the same name. (e.g. "NewMaterial" again)

It appears to run a command that doesn't work, resulting in error dialog:

> Git command failed. Please check your connection and try again, or check the output log for more information.

followed by:

> Failed to revert package which was marked for delete.

and the asset then fails to construct.

As I understand it, the command that is failing seems to be this rm while pre-construct checks are being run for the asset:
https://github.com/ProjectBorealis/UEGitPlugin/blob/d96fad8a5d57c775de28b6a9eec81f1776f7f961/Source/GitSourceControl/Private/GitSourceControlOperations.cpp#L517-L524
There appears to be a revert command that is attempting to rm the file, but the file does not exist because it's not created yet, so it fails.

It seems I can work around this by removing the rm command entirely, though I'm not sure what else I might be breaking by doing this.

Any help appreciated, thanks!

**Comment by mastercoms** [comment]
Thanks for the report, we're currently low bandwidth for tooling like this but hopefully will be able to pick this up sometime eoon
