### ISSUE TITLE
Repository root should be project root

### ISSUE THREAD

**Issue by cevanno** [ProjectBorealis/UE4GitPlugin#37]
I have a UE pixel streaming project which consists of a UE project but also a web page that has an iframe on it that presents the UE pixel stream. We setup the project directory at the top level to have a /UE and /Web subfolder because these two have to stay in sync. However now that the UE project is not at the top level this plugin stops working properly.  What happens is this: UE checkout is LFS locking properly and all users see a lock update pretty fast. When Submitting change we provide the checkin comment but then the status dialog says "Reverting Source Control", not the normal message.  This takes a while so I think its actually doing a commit/push but then it reports Success (but no Commit message) and that commit never appears on the remote repo.  The files are unlocked and remain locally changed but no updates are on the remote repo.
Developers see Success and think they've checked in files but really it successfully did nothing.

**Comment by mastercoms** [comment]
Showing reverting source control while submitting is normal, part of Unreal. The problem is that the plugin assumes the Content folder is at the root of the repo. Unfortunately I don't have time to address this workflow at the moment but you can look into modifying the plugin to add /UE/ to RepositoryRoot, or using a submodule for the UE repo. Might have time later to do it myself but not guaranteed.

**Comment by cevanno** [comment]
I modified GitSourceControlRevision.cpp line 30 to append the subfolder and rebuilt the plugin but the change seems to have had no effect. Did I modify the correct thing? I tried:
`const FString PathToRepositoryRoot = Provider.GetPathToRepositoryRoot() +  "/UE/";`
and
`const FString PathToRepositoryRoot = Provider.GetPathToRepositoryRoot() +  "\\UE";`

**Comment by cevanno** [comment]
Thinking that the the best way is to GetPathToProject (the UE project) and not the repository root. This lets any UE project at any level at or below the repo root work.  git will commit and push from subfolders no problem.  That said, manually (in bash cli outside of UE) doing a git add/commit/push from the repo root works fine so, as you say, the plugin itself has this assumption and there may be more tentacles to it.

**Comment by mastercoms** [comment]
This is correct, I will look into this. A bit complicated and scary to change but I should be able to fix it.
