### ISSUE TITLE
Plugin causes packaging project (cooking) to fail

### ISSUE THREAD

**Issue by cevanno** [ProjectBorealis/UE4GitPlugin#38]
I'm a new user so assume this is a known issue and simple fix but I can't find an answer. File>Package project>Win64 fails immediately when this plugin exists in the project /Plugins folder.  Temporarily removing the GitSourceControl.uplugin file (removing the plugin) allows the build to complete. It has to be removed this way because disabling the plugin in UE is not enough and the build still fails. Here's a piece of the output log

```
UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject= XXXXXX.uproject BuildCookRun -nocompileeditor -installed -nop4 -project=XXXXXXX.uproject -cook -stage -archive -archivedirectory=E:/XXXXXX/Str
eamingBuilds -package -ue4exe=C:\UnrealVersions\UE_4.27\Engine\Binaries\Win64\UE4Editor-Cmd.exe -compressed -ddc=InstalledDerivedDataBackendGraph -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -clientconfig=Development -utf8output
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for E:\XRMG\source\Unreal\EagleSSCommsTester\EagleSSCommsTester.uproject
UATHelper: Packaging (Windows (64-bit)): **ERROR: System.ArgumentException: An item with the same key has already been added.**
```
This plugin is very complete. It even has the git-lfs.exe so I had to add an exception to the .gitignore to prevent it from being stripped but maybe its "too complete"? Something is conflicting with UE engine files.  Is there a better solution than I have found?

**Comment by mastercoms** [comment]
What version of the plugin did you download?

**Comment by cevanno** [comment]
Version 3.03 as per the .uplugin file

**Comment by mastercoms** [comment]
Could you try 3.04?

**Comment by cevanno** [comment]
Version 3.04 results in the same error in clean project.

**Comment by mastercoms** [comment]
Can you give me full reproduction instructions? How are you invoking the build?

**Comment by cevanno** [comment]
Just tried again with 306 and same issue. Found this is a problem for blueprint projects but maybe not C++ projects
This testing is being done with UE4.27.2. I find that the plugin needs to be rebuilt before use so the first thing I do is create a new blank UE C++ project. Create /Plugins folder and unzip UEGitPlugin-release306.zip to create /UEGitPlugin-release306.
Then open this project and UE will rebuild the plugin then open the project.
In this C++ project  File>PackageProject>Win64 Select a new /PackagedBuilds folder. This succeeds.

My projects are blueprint projects so I copy the /Plugins folder from the working C++ project to my project where it fails.  To eliminate my project as being the culprit you can follow these steps to reproduce:

1. Create new blueprint blank project and open it
2. File>PackageProject>Win64 Select a new /PackagedBuilds folder
3. Observe build success. Close the project.
4. Create /Plugins folder and copy the /UEGitPlugin-release folder there from the C++ project where it was recently compiled
5.  Open the project.  File>PackageProject>Win64 Select a new /PackagedBuilds folder
6. Observe failure with details as provided in this thread

**Comment by mastercoms** [comment]
Thanks, I'll look into it!
