### ISSUE TITLE
Adding extracted folder to /Plugins causes UE to crash on open

### ISSUE THREAD

**Issue by alexvng** [ProjectBorealis/UE4GitPlugin#39]
I cannot install this plugin. I receive this error each time:

![image](https://user-images.githubusercontent.com/18650322/170185138-0dca4740-3386-4971-8692-f9eee821cb1a.png)
**Alt text description:** A Windows message box with the following text and an OK button.
`Plugin 'GitSourceControl' failed to load because 'GitSourceControl' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.`

I am using the latest release, v3.0.3, and a stock install of UE 4.27.2 fresh from the Epic Games client.

I tried both installation methods:
1. I tried pasting the unzipped folder into the `/Plugins` folder of my project. I could open the project selection window, but when I selected my project, I got that error message.
2. I moved the unzipped folder to the `/Engine/Plugins` folder of my UE4.27 installation and renamed the `.uplugin` in `/Engine/Plugins/Developer/GitSourceControl` to `.disabled`, as stated in instructions. Afterwards, I could not even open the engine itself without receiving that error message.

Any guidance? Thanks, and let me know if I should provide any more info.

**Comment by mastercoms** [comment]
Did you compile the plugin?

**Comment by alexvng** [comment]
Whoops, that's probably why. I'll try again and get back to you - missed that step.

**Comment by alexvng** [comment]
I don't see instructions on how to compile in the README. How would I go about doing that?

**Comment by stilobique** [comment]
Install Visual Studio, on your unreal project start, a new popup ask to recompile your project.
About visual,  [you can find more instruction here](https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/DevelopmentSetup/VisualStudioSetup/).
