### ISSUE TITLE
Register status branches

### ISSUE THREAD

**Issue by CubeElement** [ProjectBorealis/UE4GitPlugin#41]
Hi,
i try to implement RegisterStateBranches(), but won't pass `if (SourceControlModule.IsEnabled())` condition, actually. 

On 	`UE_LOG(LogTemp, Warning, TEXT("SCModule is enabled status: %s"), ( SourceControlModule.IsEnabled() ? TEXT("true") : TEXT("false") ));` i'm getting in OutputLog `LogTemp: Warning: SCModule is enabled status: false`.
But at the same time `SourceControlModule.GetProvider().GetName()` is returning `Git`.

I put it into custom UnrealEd module like so
```
#include "UEGitTestProjectEngine.h"
#include "ISourceControlModule.h"
#include "ISourceControlProvider.h"

UUEGitTestProjectEngine::UUEGitTestProjectEngine(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}
void UUEGitTestProjectEngine::Init(IEngineLoop* InEngineLoop)
{
	Super::Init(InEngineLoop);
 
	// Update source control settings and register in case the provider changes
	UpdateSourceControlSettings();
	ISourceControlModule::Get().RegisterProviderChanged(FSourceControlProviderChanged::FDelegate::CreateLambda([this](ISourceControlProvider& OldProvider, ISourceControlProvider& NewProvider) {
		if (NewProvider.GetName() == FName("Git"))
		{
			this->UpdateSourceControlSettings();
		}
	}));
}
 
void UUEGitTestProjectEngine::UpdateSourceControlSettings()
{
	// Register state branches
	ISourceControlModule& SourceControlModule = ISourceControlModule::Get();
	UE_LOG(LogTemp, Warning, TEXT("Source Control Module is enabled status: %s"), ( SourceControlModule.IsEnabled() ? TEXT("true") : TEXT("false") ));
	UE_LOG(LogTemp, Warning, TEXT("Source Control Provider name: %s"), ( *(SourceControlModule.GetProvider().GetName()).ToString() ));
	ISourceControlProvider& SourceControlProviderTest = SourceControlModule.GetProvider();
	if (SourceControlModule.IsEnabled())
	{
		ISourceControlProvider& SourceControlProvider = SourceControlModule.GetProvider();
	 	// Order matters. Lower values are lower in the hierarchy, i.e., changes from higher branches get automatically merged down.
	 	// (Automatic merging requires an appropriately configured CI pipeline)
	 	// With this paradigm, the higher the branch is, the stabler it is, and has changes manually promoted up.
	 	const TArray<FString> Branches {"origin/develop", "origin/main"};
	 	SourceControlProvider.RegisterStateBranches(Branches, TEXT("Content"));
	}        
}
```
i am seeking for advice what is going wrong here, is it something in the UnrealEd module (like loading order, so it would initialize ISourceControlModule later) or other places?

**Comment by mastercoms** [comment]
This might be a regression with async init, thank you! I think it's possible to just skip the IsEnabled check as a workaround. Let me know if this works.

**Comment by CubeElement** [comment]
@mastercoms i commented the line with condition check to make it work as you suggested
![image](https://user-images.githubusercontent.com/70653782/172557771-7e77cf98-b390-4368-9977-752077fc0b9d.png)
and now i am able to see a branch status finally (don't know if ".. CL: Unknown.." is meant to be so)
thanks for a tip : ) tbh for today i haven't noticed and can't foresee any possible consequences of that workaround

**Comment by mastercoms** [comment]
Thanks for the report, and yes, at the moment it's not implemented to see the CL.
