### ISSUE TITLE
Unlock doesn't happen

### ISSUE THREAD

**Issue by Stals** [ProjectBorealis/UE4GitPlugin#43]
HI,
If you Check Out a file by right-clicking on it, then you revert - often it works fine ("git lfs unlock" does happen).

When I go to modify the file with bPromptForCheckoutOnAssetModification enabled, it is locked correctly (looking at "git lfs locks"), but when I try to revert it, it does revert but fails to unlock.

It still has a yellow checkmark, and "git lfs locks" still reports it as locked, but when GitSourceControlUtils::GetLockedFiles is called inside Revert, it is not counted as locked and isn’t unlocked. So I’m stuck with a locked file.

Also, after that the “Revert” button when you right-click the asset just disappears. 
And so I get a file that is locked, that has a yellow checkmark, but there is no way to unlock it.

Also, sometimes when I just Check Out the files on my own, the revert then fails too, and the same “locked, with yellow checkmark, but no Revert button” situation happens as well.

When I try to "Submit Content", the lock also remains (which is probably the same issue because of the GitSourceControlUtils::GetLockedFiles behavior)

Also, when I Check Out the file from a prompt while modifying it, this error sometimes appears:
![image](https://user-images.githubusercontent.com/472089/173017492-1710c2c2-84af-4214-8b4c-6304352c36e3.png)

I don’t have a Windows machine so I’m unsure if this is a general issue, or a Mac one. Still, it becomes impossible to use the plugin

Unreal version: 5.0.2
MacOS: 12.3
Plugin version: 3.04

The git repository was created beforehand, without the setup inside the plugin.

Initially, mac version didn’t compile, but fixes similar to these https://github.com/ProjectBorealis/UEGitPlugin/pull/42 helped

**Comment by mastercoms** [comment]
Hi, I believe the mac lfs binaries are outdated, we are working on this over at https://github.com/ProjectBorealis/git-lfs, but tests are failing at the moment.

**Comment by mastercoms** [comment]
Closing this in favor of #44
