### ISSUE TITLE
Git LFS not up to date

### ISSUE THREAD

**Issue by markusstephanides** [ProjectBorealis/UE4GitPlugin#44]
Hi!

Really good work with your refactoring and the improved features!

Regarding the LFS Binary, is there a reason for having an old version of it in the repository instead of using the most recent ones (I believe version 3 is already out)?

Thanks!

**Comment by mastercoms** [comment]
We use our own fork of LFS which adds multithreading for multiple locks/unlocks. It's a work in progress to get it up to date with the latest version (tests failing): https://github.com/ProjectBorealis/git-lfs

**Comment by markusstephanides** [comment]
Do I have to use that fork in order for UEGitPlugin to run correctly or is it optional if one wants the multithreaded lock/unlock support?

**Comment by mastercoms** [comment]
The plugin is set up to use that executable. It won't work without modifications if you remove it.

**Comment by markusstephanides** [comment]
Okay, thanks!

**Comment by markusstephanides** [comment]
Reopened since I guess this issue will be used to track the status of the Git LFS binary update

**Comment by mastercoms** [comment]
Fixed in df6c48b9a92431fb2be8865fa5af9a75362a01d0, needs more testing before released
