### ISSUE TITLE
"Non-unique symbol" warning in Live Coding

### ISSUE THREAD

**Issue by ConorVernon** [ProjectBorealis/UE4GitPlugin#46]
When opening the editor with Live Coding enabled in 4.27, the window spams the following warning:
`Non-unique symbol _volmd found in COFF file C:\...\Plugins\UEGitPlugin\Intermediate\Build\Win64\UE4Editor\Development\GitSourceControl\Module.GitSourceControl.cpp.obj. Do not change the order of these variables while live coding, or consider upgrading to a newer compiler (VS 2015 or later)`
![image](https://user-images.githubusercontent.com/22355454/175913383-dbd771d3-5796-4896-b7b1-c821106c0aca.png)

It appears to be benign, I've not noticed any negative effects as of yet. But I thought I'd bring it to your attention regardless.

**Comment by mastercoms** [comment]
Yeah I believe this is just a compiler issue which is resolved in later versions of Unreal.
