### ISSUE TITLE
File doesnt save when submited and engine is restarted [UE5]

### ISSUE THREAD

**Issue by vaporvee** [ProjectBorealis/UE4GitPlugin#52]
When i submit something through Source Control with UE5 with the plugin and then restart the engine i cant save the submitet file again. Everything else works just fine. Idk if its a problem that the .gitattributes file maybe gets ignored? 

![grafik](https://user-images.githubusercontent.com/80621863/180643879-d6a17647-3ed2-4709-9991-873cb9c569b0.png)

**Comment by mastercoms** [comment]
Is this a checked out file?

**Comment by vaporvee** [comment]
Yes checked out

**Comment by mastercoms** [comment]
I've potentially fixed this in the latest commit to not happen again, but you'll probably have to go into the properties of the uasset and uncheck Read Only in windows file explorer to reverse the bug.
