### ISSUE TITLE
Source control is disabled even after enabling it

### ISSUE THREAD

**Issue by mhjort** [ProjectBorealis/UE4GitPlugin#55]
When I enable source control and accept settings using existing git repository I don't get any errors with that operation. However, I cannot see any symbols in Content Drawer. If I choose again `Connect to Source Control` from the menu it says that Provider is None and source control is disabled. 

I have also tried to restart the editor after choosing Git LFS 2. The results are the same. It always says that source control is disabled. I checked that `SourceControlSettings` file has been updated with the following contents:

```
[SourceControl.SourceControlSettings]
Provider=Git LFS 2

[GitSourceControl.GitSourceControlSettings]
BinaryPath=C:\Program Files\Git\bin\git.exe
UsingGitLfsLocking=True
LfsUserName=My name
```

I found that after enabling the Source Control I can open `View Changelists` from the menu. However, it generates following error to the log:

```
Operation 'UpdateChangelistsStatus' not supported by source control provider 'Git LFS 2'
```

I am using Unreal Engine 5.0.3 in Windows 11.

**Comment by mastercoms** [comment]
I'm not so sure why this would happen, did you copy git-lfs bins in the plugin folder correctly?

**Comment by mhjort** [comment]
I think it is related to my encoding. Somehow my user name gets scrambled. See picture below (My name should be Markus but it just shows weird characters)

![image](https://user-images.githubusercontent.com/94291/184627108-f06761bb-2984-40f8-a247-be145d0393ac.png)

**Comment by mhjort** [comment]
I was able to get it working by just ignoring the weird user name proposal.
