### ISSUE TITLE
SSH required for plugin to function?

### ISSUE THREAD

**Issue by jeffason** [ProjectBorealis/UE4GitPlugin#56]
We've onboarded several new devs recently that attempted to authenticate using PAT over HTTPS rather than SSH.  The plugin would fail with errors like this:
![image](https://user-images.githubusercontent.com/3349419/184170685-ea42038f-6571-4e1f-ad68-c7bd3d574703.png)

Our workaround is to have them switch their remote to SSH and authenticate with a private key pair.  Is this a known issue or any ideas what we're doing wrong?

**Comment by mastercoms** [comment]
We all use HTTPS authentication, using Git Credential Manager.

**Comment by jeffason** [comment]
Ok, glad to hear it's working for some people. I'll do some more digging to see if I can get it to work.  Will close this issue for now
