### ISSUE TITLE
With one file per actor unreal doesn't checkout newly placed actors - only way to checkout is using "Checkout Modified Files"

### ISSUE THREAD

**Issue by sZXZ** [ProjectBorealis/UE4GitPlugin#61]
With one file per actor unreal doesn't checkout newly placed actors 

There is workaround to use "Checkout Modified Files" button

I think it's related to https://github.com/ProjectBorealis/UEGitPlugin/issues/53

**Comment by mastercoms** [comment]
I've been looking around and I don't think Unreal allows for this besides for automatically checkout on asset modification or prompt for checkout on asset modification. So I don't think this is possible for the plugin.
