### ISSUE TITLE
Unreal Engine complains that a local file is writable, but not checked out, even though it is

### ISSUE THREAD

**Issue by useronym** [ProjectBorealis/UE4GitPlugin#65]
![Screenshot 2022-11-03 154534](https://user-images.githubusercontent.com/4563753/199753881-c6179058-a824-4744-9bd8-6aca9dc9a2a3.png)

Saving an asset triggers the above warning, even though the file is checked out.

**Comment by mastercoms** [comment]
What is your timing in terms of saving an asset vs. checking it out? I know in some cases, like automatic checkout or some prompts, the file will save prior to it having read it is checked out. Perhaps in UE5 these things got worse.

**Comment by useronym** [comment]
I checked out the file about an hour ago, and every time I save it in the Editor, I get the same error.

**Comment by mastercoms** [comment]
I think this is because of some issue which also causes #64.
