### ISSUE TITLE
difference from built-in git plugin

### ISSUE THREAD

**Issue by chiptus** [ProjectBorealis/UE4GitPlugin#73]
what is the difference from the currently builtin git plugin? screenshots look the same, although I'm not 100% the built-in supports file locking. Is this plugin working with UE4.27?

**Comment by mastercoms** [comment]
The differences from the Git LFS 2 plugin are listed under features: https://github.com/ProjectBorealis/UEGitPlugin#features

There is not much in terms of new UI besides the status branch support for remote branches in the screenshots.

The [Git LFS 2 plugin](https://github.com/SRombauts/UEGitPlugin)'s differences from the built-in plugin is that it supports file locking and has some misc. improvements.
