### ISSUE TITLE
Moved Files getting marked for add but are read-only

### ISSUE THREAD

**Issue by eXifreXi** [ProjectBorealis/UE4GitPlugin#85]
I just wanted to make a proper single-issue post for this, so it doesn't vanish inside other issues.

I'm on the latest commit and have no custom changes on the plugin. Using 5.1.1. Happened with 5.0 and 5.1 too I believe.

I'm relatively sure this is a 100% repro. If I move existing files between folders and clean up their redirectors, those files get in an annoying state where they are **marked for add** but **read-only**.

Since they are **marked for add** I can't check them out anymore to make them writeable. I'm not sure how exactly this works, but I assume that somewhere UE is automatically marking those files for **add**, which Git handles properly, but it's somewhere lacking a call to remove the read-only flag.

![image](https://user-images.githubusercontent.com/8512512/219964208-2ba5614f-a250-4e72-a5cb-5cbe886d7bf8.png)
![image](https://user-images.githubusercontent.com/8512512/219964219-2d34a368-c158-4a75-bd8b-19c147671622.png)
![image](https://user-images.githubusercontent.com/8512512/219964259-f426470e-1cbb-4cca-ae28-a7f4ac236f36.png)
![image](https://user-images.githubusercontent.com/8512512/219964433-3712334d-9574-4bbb-9c1e-a120a4575256.png)

Above 5 files were moved one folder deeper (cause it got too many files). Fixed up redirectors, now they are **marked for add** but  **read-only**. I have to manually remove the read-only flag or commit them first. That shouldn't be a requirement to my knowledge.

Let me know if you need anything else (:

**Comment by eXifreXi** [comment]
Also, after fixing up related redirectors (PlayerControllers, similar reason), all the files I deleted manually and the files that were deleted by the moving (the GameModes) suddenly reappeared in their original folder (moved files still exist). Might be a side-effect.

**Comment by haptx-peyton** [comment]
I've encountered this issue before too! Here's what fixed it for me:
Go to **Edit > Editor Preferences > Loading & Saving >  Source Control** and uncheck **Add New Files when Modified**.

Let me know if that helps!
(You may have to do the move again by reverting your changes, also.)

**Comment by mastercoms** [comment]
Oh, this is the setting we use! Thanks for spotting the difference, will test with that now.

**Comment by mastercoms** [comment]
I've added this configuration setting to the README, let me know if this is still an issue in any other cases.
