### ISSUE TITLE
Feature Request: Prevent locking outdated files

### ISSUE THREAD

**Issue by miltoncandelero** [ProjectBorealis/UE4GitPlugin#88]
Hello!
First of all, I want to say that this is a git-lfs problem and not a problem of this plugin but a case can be made for having an extra check in place.

Listen to this story: `Julia` and `Matt` are working in the same repo. They start at the same point in the history, say at `Initial Commit`. The following happens in order:
- `Julia` locks `Player.uasset`
- `Julia` modifies `Player.uasset`
- `Julia` commits, pushes and unlocks `Player.uasset`
- `Matt` doesn't know this happenned and wants to modify `Player.uasset`
- `Matt` attempts to lock `Player.uasset` WITHOUT PULLING (we might argue it's his fault)
- `Matt` succeeds locking an outdated version of `Player.uasset` (you see where this is going)
- `Matt` modifies `Player.uasset`
- `Matt` commits `Player.uasset`
- `Matt` is hit with a conflict while trying to pull/push `Player.uasset`

Matt will say: "I didn't touch any locked file, I requested the lock and used the file after it was locked to my name", however they were outdated.

A simple solution would be to run something like `git fetch && git diff --name-only <remote>/<branch>` and make sure the file we are attempting to lock file is up to date (meaning it's not in the diff file list). Otherwise, inform the user that this file is locked by reason of being stuck in the past. An update is needed to lock it.

**Comment by miltoncandelero** [comment]
Well, I realized we do have a yellow exclamation mark for that. As long as people run the fetch command then they shouldn't be able to lock the file 🤦

**Comment by mastercoms** [comment]
The plugin automatically fetches regularly, no need to run fetch yourself.
