### ISSUE TITLE
Requesting new hotfix version for updated gitignore. 

### ISSUE THREAD

**Issue by billy-agate** [ProjectBorealis/UE4GitPlugin#95]
Is there any plan on creating a new hotfix version for updated gitignore ? 

when does the next release tag are planned to release ?

i am currently guiding my team to install git plugin. 
and having to guide them through download with `Clone` button seems to raise lots of confusions

**Comment by mastercoms** [comment]
I was waiting for #54 but I can do one now since it's priority like you say
