### ISSUE TITLE
Working with file that are made write-able but not Checked Out

### ISSUE THREAD

**Issue by as3mbus** [ProjectBorealis/UE4GitPlugin#97]
Hello, I am asking some questions and some discussion if any. 

Is there a way to mark a modified file but not-checked-out with a particular symbol?

or is there a quick menu to flush (restore) all modified but not-checked-out file ?

the use case is like below : 

1. i'd like to modify some of my asset value without actually checking them out for testing purpose.
2. after a modification made by other user I'd like to revert my file to original state and pull from the latest changes.
3. when I did this it usually ends up with error as git lfs tried to stash and restore my changes and result in conflicting merge

Thank You in advance 😄

**Comment by mastercoms** [comment]
You can use the content browser filters for source control. Icons will be improved in 5.2.

**Comment by as3mbus** [comment]
These solutions should do for now. 

and does icon mentioned are change made in unreal engine or in the plugins ?

**Comment by mastercoms** [comment]
In engine

**Comment by mastercoms** [comment]
Is this still an issue with the latest release?
